services:
  - type: web
    name: deep-night-pharmacy-bar
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
